# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spx2gB5njKKCp5oVaCt0Lj0z4FdvrPcL
"""

import networkx as nx
import matplotlib.pyplot as plt

vertices = range(1,10)
edges= [(7,2),(2,3),(7,4),(4,5),(7,3),(7,5),(1,6),(1,7),(2,8),(2,9)]

G = nx.Graph()
G.add_nodes_from(vertices)
G.add_edges_from(edges)
pos=nx.spring_layout(G)

nx.draw_networkx_nodes(G, pos, nodelist=[1,4,3,8,9], node_color='g', node_size=1300)
nx.draw_networkx_nodes(G, pos, nodelist=[2,5,6,7], node_color='r', node_size=1300)
nx.draw_networkx_edges(G, pos, edges, width=3, alpha=0.5, edge_color='b')
labels={}
labels[1]=r'1 NF'
labels[2]=r'2 F'
labels[3]=r'3 NF'
labels[4]=r'4 NF'
labels[5]=r'5 F'
labels[6]=r'6 F'
labels[7]=r'7 F'
labels[8]=r'8 NF'
labels[9]=r'9 NF'
nx.draw_networkx_labels(G, pos, labels, font_size=10)

#Gambar Nodes dan edges beserta labelnya mengggunakan NetworkX. NF berwarna hijau,sedangkan F berwarna merah
nx.draw_networkx_nodes(G, pos, nodelist=[1,4,3,8,9], node_color='g', node_size=1300)
nx.draw_networkx_nodes(G, pos, nodelist=[2,5,6,7], node_color='r', node_size=1300)
nx.draw_networkx_edges(G, pos, edges, width=3, alpha=0.5, edge_color='b')
labels={}
labels[1]=r'1 NF'
labels[2]=r'2 F'
labels[3]=r'3 NF'
labels[4]=r'4 NF'
labels[5]=r'5 F'
labels[6]=r'6 F'
labels[7]=r'7 F'
labels[8]=r'8 NF'
labels[9]=r'9 NF'

labels = {node: f'{node} ({dos_values[node]})' for node in G.nodes()}

nx.draw_networkx_labels(G, pos, labels, font_size=10)
def calculate_dos(node):
  dos = 0
  for neighbor in G.neighbors(node):
    if labels[neighbor] != labels[nodes]:
      dos += 1
  return dos
dos_values = {node: calculate_dos(node) for node in G.nodes()}

# Membuat graph (jaringan sosial)
G = nx.Graph()

# Menambahkan vertices dan edges
vertices = range(1, 10)
edges = [(7, 2), (2, 3), (7, 4), (4, 5), (7, 3), (7, 5), (1, 6), (1, 7), (2, 8), (2, 9)]
G.add_nodes_from(vertices)
G.add_edges_from(edges)

# Menghitung derajat setiap node
degree_values = dict(G.degree())

# DOS values (derajat tanpa normalisasi)
dos_values = {node: degree for node, degree in degree_values.items()}

# Menampilkan DOS values
print("DOS values:")
for node, dos in dos_values.items():
  print(f"{node}: {dos}")

# Normalisasi nilai derajat ke dalam rentang 0-9
max_degree = max(degree_values.values())

# Menghitung DOS values (derajat yang dinormalisasi)
normalized_dos_values = {node: round((degree / max_degree) * 9, 2) for node, degree in degree_values.items()}

# Menampilkan DOS values (derajat yang dinormalisasi)
print("\nNormalized DOS values:")
for node, normalized_dos in normalized_dos_values.items():
  print(f"{node}: {normalized_dos}")

# Latihan 1

vertices = range(1, 11)
edges = [(1, 2), (1, 7), (2, 6), (2, 3), (3, 6), (4, 3), (5, 6), (6, 7), (7, 8), (7, 9), (7, 10), (8, 9)]

G = nx.Graph()

G.add_nodes_from(vertices)
G.add_edges_from(edges)
pos = nx.spring_layout(G)

# Gambar Nodes dan Edges beserta labelnya menggunakan NetworkX. NF berwarna hijau, sedangkan F berwarna merah.
nx.draw_networkx_nodes(G, pos, nodelist=[2, 3, 6, 8, 9], node_color='g', node_size=1300)
nx.draw_networkx_nodes(G, pos, nodelist=[1, 4, 5, 7, 10], node_color='r', node_size=1300)
nx.draw_networkx_edges(G, pos, edges, width=3, alpha=0.5, edge_color='b')
labels = {}
labels[1] = r'1 F'
labels[2] = r'2 NF'
labels[3] = r'3 NF'
labels[4] = r'4 F'
labels[5] = r'5 F'
labels[6] = r'6 NF'
labels[7] = r'7 F'
labels[8] = r'8 NF'
labels[9] = r'9 NF'
labels[10] = r'10 F'

nx.draw_networkx_labels(G, pos, labels, font_size=10)

# Latihan 2

vertices = range(1, 14)
edges = [(1, 2), (1, 3), (2, 3), (2, 12), (3, 12), (3, 11), (3, 10), (3, 4), (4, 6), (4, 5), (4, 7), (5, 6), (5, 7), (5, 8), (6, 9), (7, 8), (8, 9), (10, 11), (11, 12), (12, 13)]

G = nx.Graph()

G.add_nodes_from(vertices)
G.add_edges_from(edges)
pos = nx.spring_layout(G)

# Gambar Nodes dan Edges beserta labelnya menggunakan NetworkX. NF berwarna hijau, sedangkan F berwarna merah.
nx.draw_networkx_nodes(G, pos, nodelist=[4, 5, 6, 7, 8, 9, 13], node_color='g', node_size=1300)
nx.draw_networkx_nodes(G, pos, nodelist=[1, 2, 3, 10, 11, 12], node_color='r', node_size=1300)
nx.draw_networkx_edges(G, pos, edges, width=3, alpha=0.5, edge_color='b')
labels = {}
labels[1] = r'1 F'
labels[2] = r'2 F'
labels[3] = r'3 F'
labels[4] = r'4 NF'
labels[5] = r'5 NF'
labels[6] = r'6 NF'
labels[7] = r'7 NF'
labels[8] = r'8 NF'
labels[9] = r'9 NF'
labels[10] = r'10 F'
labels[11] = r'11 F'
labels[12] = r'12 F'
labels[13] = r'13 NF'

nx.draw_networkx_labels(G, pos, labels, font_size=10)