# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U78e23Nz66S8ij8cH5HHiJ2DMN8YzqnO
"""

pip install pulp

import pulp
model = pulp.LpProblem("ProfitMaximisingProblem", pulp.LpMaximize)

A = pulp.LpVariable('A', lowBound=0, cat='integer')
B = pulp.LpVariable('B', lowBound=0, cat='integer')

model += 4200 * A + 2800 * B, 'Profit'
model += 3 * A + 2 * B <= 20
model += 4 * A + 3 * B <= 30
model += 4 * A + 3 * B <= 44

model.solve()
pulp.LpStatus[model.status]

print (A.varValue)
print (B.varValue)

print (pulp.value(model.objective))

# 4x + 3y = 34
import pulp

# Membuat objek masalah optimasi
model = pulp.LpProblem(name="Pemecahan_Persamaan", sense=pulp.LpMinimize)

# Membuat variabel x dan y
x = pulp.LpVariable(name="x")
y = pulp.LpVariable(name="y")

# Menambahkan batasan
model += 4 * x + 3 * y == 34

# Menyelesaikan masalah
model.solve()

# Menampilkan hasil
print("Status:", model.status)
print("Nilai x =", x.varValue)
print("Nilai y =", x.varValue)

# 4x + 3y = 34
import pulp

model = pulp.LpProblem("Pemecahan_Persamaan", sense=pulp.LpMinimize)

x = pulp.LpVariable(name="x")
y = pulp.LpVariable(name="y")

model += 5 * x + y == 37

model.solve()

print("status:", model.status)
print("Nilai x =", x.varValue)
print("Nilai y =", y.varValue)

# 4x + 3y = 34
import pulp

model = pulp.LpProblem("Pemecahan_Persamaan", sense=pulp.LpMinimize)

x = pulp.LpVariable(name="x")
y = pulp.LpVariable(name="y")

model += 4 * x + 12 * y == 38

model.solve()

print("status:", model.status)
print("Nilai x =", x.varValue)
print("Nilai y =", y.varValue)

# 4x + 3y = 34
import pulp

model = pulp.LpProblem("Pemecahan_Persamaan", sense=pulp.LpMaximize)

x = pulp.LpVariable(name="x")
y = pulp.LpVariable(name="y")

model += 4 * x + y == 21

model.solve()

print("status:", model.status)
print("Nilai x =", x.varValue)
print("Nilai y =", y.varValue)